answer_mappings = {
    "age": {
        1: "1", 2: "2", 3: "3", 4: "4", 5: "5", 6: "6", 7: "7", 8: "8",
        9: "9", 10: "10", 11: "11", 12: "12", 13: "13", 14: "14", 15: "15",
        16: "16", 17: "17", 18: "18", 19: "19", 20: "20", 21: "21", 22: "22",
        23: "23", 24: "24", 25: "25", 26: "26", 27: "27", 28: "28", 29: "29",
        30: "30", 31: "31", 32: "32", 33: "33", 34: "34", 35: "35", 36: "36",
        37: "37", 38: "38", 39: "39", 40: "40", 41: "41", 42: "42", 43: "43",
        44: "44", 45: "45", 46: "46", 47: "47", 48: "48", 49: "49", 50: "50",
        51: "51", 52: "52", 53: "53", 54: "54", 55: "55", 56: "56", 57: "57",
        58: "58", 59: "59", 60: "60", 61: "61", 62: "62", 63: "63", 64: "64",
        65: "65", 66: "66", 67: "67", 68: "68", 69: "69", 70: "70", 71: "71",
        72: "72", 73: "73", 74: "74", 75: "75", 76: "76", 77: "77", 78: "78",
        79: "79", 80: "80 or more", 0: ""
    },
    "gender": {1: "a male", 2: "a female", 3: "neither male or female", 0: ""},
    "race": {1: "white", 2: "black", 3: "Asian or Pacific Islander",
                     4: "American Indian or Alaska Native", 5: "Hispanic", 6: "", 7: "", 9: ""},
    "educ": {1: "8 grades or less (‘grade school’)", 2: "less than high school credential",
                      3: "12 grades, diploma or equivalency", 4: "12 grades, diploma or equivalency plus non-academic training",
                      5: "some college with no degree or junior/community college level degree (AA degree)",
                      6: "BA level degrees or advanced degrees incl. LLB", 8: "", 9: ""},
    "income": {1: "0 to 16 percentile", 2: "17 to 33 percentile", 3: "34 to 67 percentile",
                        4: "68 to 95 percentile", 5: "96 to 100 percentile", 0: ""},
    "union": {1: "Someone in my household belongs to a labor union.",
                       2: "No one in my household belongs to a labor union.", 0: ""},
    "religion": {1: "Protestant", 2: "Catholic", 3: "Jewish",
                          4: "neither Protestant, Catholic, nor Jewish, or non-religious", 0: ""},
    "church": {1: "every week", 2: "almost every week", 3: "once or twice a month",
                        4: "a few times a year", 5: "never", 8: "", 9: ""},
    "parents_born": {1: "Both my parents were born in USA.",
                              5: "At least one of my parents were not born in the USA.", 8: "", 9: ""},
    "home_ownership": {1: "Me and/or my family own my home.", 2: "Me and/or my family do not own my home.", 8: "", 9: ""},
    "marital": {1: "I am married.", 2: "I have never been married.", 3: "I am divorced.",
                         4: "I am separated.", 5: "I am widowed.", 7: "I have a partner, but are not married.", 8: "", 9: ""},
    "postal": {"AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California",
                        "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia",
                        "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
                        "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
                        "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
                        "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire",
                        "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York", "NC": "North Carolina",
                        "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania",
                        "RI": "Rhode Island", "SC": "South Carolina", "SD": "South Dakota", "TN": "Tennessee",
                        "TX": "Texas", "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
                        "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming"},
    "initial_party": {1: "Republican", 2: "Independent", 3: "having no political party", 4: "",
                              5: "Democrat", 8: "", 9: ""},
    "interest": {1: "not much interested", 2: "somewhat interested", 3: "very much interested", 9: "", 0: ""},
    "discuss": {0: "for no days", 1: "for one day", 2: "for two days", 3: "for three days",
                         4: "for four days", 5: "for five days", 6: "for six days", 7: "every day", 9: ""},
    "lib_cons": {1: "Liberal", 3: "Moderate ('middle of the road')", 5: "Conservative", 6: "", 9: "", 0: ""},
    "partisanship": {1: "independent", 2: "leaning independent", 3: "weak partisan", 4: "strong partisan", 0: ""}
}
